relativeURLs = true
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "The Cloud Blog"
theme = "okayish-blog-fork"
enableGitInfo = true
enableEmoji = true
enableRobotsTXT = true

# These will be used for OpenGraph, Twitter Card and Schema.org
description = "by Rahul Rai"
keywords = ["azure", "cloud", "blog", "tips", "ASP.net", "DevOps", "Web"]
images = ["/images/banner.png"]
mainSections = ["post","lab"]
paginate = 100

# This is the number of terms within a taxonomy per page
termsPaginate = 50
# Enable/disable share links (Facebook, Twitter and LinkedIn)
shareLinksEnabled = true

# Add menu items to the navigation bar as below.
# N.B. Use identifiers as the keys for translations.
[menu]

[[menu.main]]
name = "whoami"
weight = 1
url = "/whoami"

[[menu.main]]
name = "Publications"
weight = 2
url = "/authors"

[module]
    [[module.mounts]]
        source = "assets/lib/img"
        target = "static/lib/img"

[social]
    twitter = "rahulrai-in"