name: Deploy to Netlify
on:
  push:
    branches: [ master ]
defaults:
  run:
    working-directory: ./tcb
jobs:
  build_deploy:
      runs-on: ubuntu-latest
      steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
            hugo-version: '0.74.3'
            extended: true

      - name: build
        run: hugo --minify --gc

      - name: deploy
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=./tcb/public --functions=functions
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}