name: Deploy to Netlify
on:
  push:
    branches: [ master ]
defaults:
  run:
    working-directory: ./tcb
jobs:
  build_deploy:
      runs-on: ubuntu-latest
      steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
            hugo-version: '0.74.3'
            extended: true

      - name: build
        run: hugo

      - name: deploy
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: "./tcb/public"
          production-branch: master
          production-deploy: true
          deploy-message: "Deployment v${{ github.ref }}"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1